title = "Custom Gitleaks Config"

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|secret|token)[^a-zA-Z0-9]?['"]?[a-z0-9-_]{8,40}['"]?'''
tags = ["key", "API", "generic"]
