name: OWASP ZAP Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install dependencies and start React app
      - name: Start application
        working-directory: Security_Compliance_workshop-parasjain/Day2/vulnerable-react-app
        run: |
          npm install
          npm start &
          sleep 20  # wait for the app to start on http://localhost:3000

      # Step 3: Run OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:3000"
          cmd_options: "-a"

      # Step 4: Upload ZAP Report
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
